services:
  postgres:
    image: postgres:17-alpine
    container_name: inventory-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory

    ports:
      - "5432:5432"

    volumes:
      # Persistent database storage
      - postgres_data:/var/lib/postgresql/data

      # Initial SQL scripts
      - ./infra/postgres:/docker-entrypoint-initdb.d

    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: inventory-api

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/inventory?sslmode=disable

    restart: unless-stopped

volumes:
  postgres_data:
